[package]
name = "blockchain-cpp"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
reqwest = "0.12.5"